export function fetchWithAuth(url: string, options: RequestInit = {}) {
	const token = "eyJhbGciOiJIUzI1NiIsImtpZCI6IkFRT1Z1TXFUTGlXZFBYaFIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2JnYnV2cXd1cnBoc3Z6b252ZWVuLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwMGVmYjkwNC1mMWUxLTRjYTYtYjYxYS00MjQ0NGFlYjY5MTMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU3OTU4ODI4LCJpYXQiOjE3NTc5NTUyMjgsImVtYWlsIjoib21zaW5fNDdAaG90bWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoib21zaW5fNDdAaG90bWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIwMGVmYjkwNC1mMWUxLTRjYTYtYjYxYS00MjQ0NGFlYjY5MTMifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1Nzk1NTIyOH1dLCJzZXNzaW9uX2lkIjoiY2RkY2VkZmEtMTk0Yy00ZGVjLWI1NTUtN2EwODE3ZTkzNzQwIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.9RMN7W9XrWdGYOz8f_xKk3FF5uNzKfxymrdCyf_q0YU";
	const headers = {
		...options.headers,
		'Authorization': `${token}`,
		'Content-Type': 'application/json',
	};
	return fetch(url, { ...options, headers });
}